FROM ubuntu
RUN apt update && apt -y upgrade && apt-get install -y curl
RUN apt-get install build-essential -y
RUN apt install -y vim git openssh-client g++ python3 python3-pip
RUN git config --global user.email "race.carter.98@gmail.com" && git config --global user.name "roman"
RUN cd /home && git clone https://github.com/ravinamine/selfie-hacks.git
WORKDIR /home/selfie-hacks
RUN git remote set-url origin git@github.com:ravinamine/selfie-hacks.git
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
ARG SSH_PRIVATE_KEY
RUN mkdir ~/.ssh/
RUN echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
RUN chmod 600 ~/.ssh/id_rsa
RUN ssh-keyscan github.com >> ~/.ssh/known_hosts